config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'cooks/index'
  root to: "cooks#index"
  resources :cooks do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '日本料理' },
    { id: 3, name: 'イタリア料理' },
    { id: 4, name: 'フランス料理' },
    { id: 5, name: '中華料理' },
    { id: 6, name: 'トルコ料理' },
    { id: 7, name: 'ロシア料理' },
    { id: 8, name: 'ドイツ料理' },
    { id: 9, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :cooks

  end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :cook

  validates :text, presence: true
end

app/models/cook.rb
class Cook < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :cooktime

  belongs_to       :user
  has_many         :comments,  dependent: :destroy
  has_one_attached :image

  def self.search(search)
    if search != ""
      Cook.where('title LIKE(?)', "%#{search}%")
    else
      Cook.all
    end
  end

  with_options presence: true do
    validates :title
    validates :catch_copy
    validates :material
    validates :making
  end

  with_options presence: true,numericality: { other_than: 1 } do
    validates :category_id
    validates :cooktime_id
  end

end

app/models/cooktime.rb
class Cooktime < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '５分' },
    { id: 3, name: '１０分' },
    { id: 4, name: '１５分' },
    { id: 5, name: '２０分' },
    { id: 6, name: '３０分以上' },
    { id: 7, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :cooks

  end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '日本料理' },
    { id: 3, name: 'イタリア料理' },
    { id: 4, name: 'フランス料理' },
    { id: 5, name: '中華料理' },
    { id: 6, name: 'トルコ料理' },
    { id: 7, name: 'ロシア料理' },
    { id: 8, name: 'ドイツ料理' },
    { id: 9, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :users

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  has_many   :cooks   , dependent: :destroy
  has_many   :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
         
  with_options presence: true do
    validates :nickname
    validates :profile
  end
  with_options presence: true,numericality: { other_than: 1 } do
    validates :genre_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :genre_id, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to cook_path(@comment.cook)
    else
      @cook = @comment.cook
      @comments = @cook.comments
      render :"cooks/show" 
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, cook_id: params[:cook_id])
  end
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  
  def index
    @cook = Cook.all
  end

  def new
    @cook = Cook.new
  end

  def create
    @cook = Cook.create(cook_params)
    if @cook.save
       redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @cook = Cook.find(params[:id])
    unless @cook.user_id == current_user.id
       redirect_to cooks_path
    end
  end

  def update
    @cook = Cook.find(params[:id])
    if @cook.update(cook_params)
        redirect_to cook_path
    else
       render :edit
    end
  end

  def destroy
    @cook = Cook.find(params[:id])
    @cook.destroy
    redirect_to cooks_path
  end

  def show
    @cook = Cook.find(params[:id])
    @comments = @cook.comments.includes(:user)
    @comment = Comment.new
  end

  def search
    @cooks = Cook.search(params[:keyword])
  end
  

  private
  def cook_params
    params.require(:cook).permit(:title, :catch_copy, :category_id, :cooktime_id, :material, :making, :point, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
     redirect_to action: :index
    end 
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @cooks = Cook.find(@user.cook_ids)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cooks/_cook.html.erb
<div class="card">
  <%= link_to image_tag(cook.image, class: :card__img ), cook_path(cook) %>
  <div class="card__body">
    <%= link_to cook.title, cook_path(cook), class: :card__title%>
    <p class="card__summary">
      <%= cook.catch_copy %>
    </p>
    <p class="card__summary">
      <%= cook.point %>
    </p>
    <%= link_to cook.user.nickname, user_path(cook.user_id), class: :card__user %>
  </div>
</div>

app/views/cooks/_form.html.erb
<%= form_with model: @cook, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "料理名" %><br />
    <%= f.text_field :title, id:"cook_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"cook_catch_copy" %>
  </div>

  <div class="field-detail">
    <div class="form">
      <div class="weight-bold-text">料理カテゴリー
      </div>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
    </div>
  </div>
  <br />
  <div class="field-detail">
    <div class="form">
      <div class="weight-bold-text">調理時間
      </div>
    <%= f.collection_select(:cooktime_id, Cooktime.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
    </div>
  </div>

  <div class="field">
    <%= f.label :material, "材料" %><br />
    <%= f.text_area :material, class: :form__text, id:"cook_material" %>
  </div>

  <div class="field">
    <%= f.label :making, "作り方" %><br />
    <%= f.text_area :making, class: :form__text, id:"cook_making" %>
  </div>

  <div class="field">
    <%= f.label :point, "料理のワンポイント" %><br />
    <%= f.text_area :point, class: :form__text, id:"cook_point" %>
  </div>

  <div class="field">
    <%= f.label :image, "料理の画像投稿" %><br />
    <%= f.file_field :image, id:"cook_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/cooks/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">投稿料理の編集</h2>
      <%= render partial: "form" %>
    </div>
  </div>
</div>

app/views/cooks/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in?  %>
      <div class="greeting">
         こんにちは、 
      <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: :greeting__link %>
      </div>
    <% end %>
    <div class="cook__wrapper">
      <div class="cook__detail">
      <br>
      <br>
        <p class="detail__title">Pick up! cook!</p>
      </div>
    <div class="card__wrapper">
      <%= render partial: 'cook', collection: @cook %>
    </div>
  </div>
</main>

app/views/cooks/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規料理の投稿</h2>
        <%= render partial: "form" %>
    </div>
  </div>
</div>

app/views/cooks/search.html.erb
<main class="main">
  <div class="inner">
    <div class="card__wrapper">
      <% @cooks.each do |cook| %>
        <%= render partial: "cook", locals: { cook: cook } %>
      <% end %>
    </div>
  </div>
</div>

app/views/cooks/show.html.erb
<main class="main">
  <div class="inner">
    <div class="cook__wrapper">
      <p class="cook__hedding">
       <div class="cook__detail">
        <p class="detail__title">料理名</p>
        <p class="card__summary"><%= @cook.title %></p>
       </div>
        <div class="cook__manage">
        <% if user_signed_in? && current_user.id == @cook.user_id %>
          <%= link_to "編集する", edit_cook_path(@cook.id), class: :cook__btn %>
          <%= link_to "削除する", cook_path(@cook.id), method: :delete, class: :cook__btn %>
        <% end %>
        </div>
      <div class="cook__image">
        <%= image_tag @cook.image %>
      </div>
      <div class="cook__body">
        <div class="cook__detail">
          <p class="detail__title">材料</p>
          <p class="detail__message">
          <p class="card__summary"><%= @cook.material %>
          </p>
        </div>
        <div class="cook__detail">
          <p class="detail__title">作り方</p>
          <p class="detail__message">
          <p class="card__summary"><%= @cook.making %>
          </p>
        </div>
        <div class="cook__detail">
          <p class="detail__title">料理のワンポイント</p>
          <p class="detail__message">
          <p class="card__summary"><%= @cook.point  %>
          </p>
        </div>
        <div class="cook__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
          <p class="card__summary"><%= @cook.catch_copy %>
          </p>
        </div>
        <div class="cook__detail">
        <p class="detail__title">投稿者</p>
        </div>
        <%= link_to @cook.user.nickname, root_path, class: :cook__user %>
      </div>
      <div class="cook__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@cook, @comment], local: true) do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text, id:"comment_text" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
           <% end %>  
        <% end %> 
        <ul class="comments_lists"> 
            <li class="comments_list">
              <h4>＜コメント一覧＞</h4>
              <% @comments.each do |comment| %>
                <p>
                  <%= comment.text %>
                  <%= link_to "#{comment.user.nickname}", user_path(comment.user_id), class: :comment_user %>
                </p>
              <% end %>
            </li>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>
  
  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right"> 
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__btn %>
              <%= link_to "レシピ投稿", new_cook_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %> 
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Cook App All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}の情報" %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">得意ジャンル料理</th>
            <td class="table__col2"><%= @user.genre.name %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの投稿レシピ" %>
      </h2>
      <div class="user__card">
        <%= render partial: 'cooks/cook', collection: @cooks %>
      </div>
    </div>
  </div>
</div>